basePath: /
host: localhost:8081
info:
  contact: {}
  description: 这是Golang开发的简单聊天Demo
  title: Gin_Chat Demo API Docs
  version: "1.0"
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user:
    delete:
      description: 删除用户
      parameters:
      - description: 用户ID
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: code","msg","data"}
          schema:
            type: string
        "500":
          description: code","msg","data"}
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户管理
    post:
      description: 创建用户
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      - description: 确认密码
        in: query
        name: rePassword
        type: string
      - description: 手机号码
        in: query
        name: phone
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code","msg","data"}
          schema:
            type: string
        "500":
          description: code","msg","data"}
          schema:
            type: string
      summary: 创建用户
      tags:
      - 用户管理
  /user/list:
    get:
      description: 获取用户列表
      produces:
      - application/json
      responses:
        "200":
          description: code","data"}
          schema:
            type: string
        "500":
          description: code","data"}
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - 用户管理
swagger: "2.0"
